spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    username: name
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      format-sql: true

  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        interceptor:
          classes: "class"
      buffer-memory: 81920
      retries: 1
      batch-size: 10

    consumer:
      bootstrap-servers: 127.0.0.1:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        interceptor:
          classes: "class"

logging:
  level:
    root: warn