
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cloud-native-java-with-k8s-livelessons/configuration-config.git
          #uri: file:///${HOME}/Desktop/source/
        default-label: main
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8888