spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    username: name
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true